### ISSUE TITLE
Link to Monitoring page in breadcrumbs is broken

### ISSUE THREAD

**Issue by fasterthan** [IBM-Bluemix-Docs/SLmonitoring#12]
At the top of the page there is a breadcrumb that looks like "IBM Cloud / Monitoring" and clicking on the "Monitoring" link leads to a 404

**Comment by William-Scott-Holmes** [comment]
I'm currently investigating this issue - thanks for the feedback!
-Scott

**Comment by William-Scott-Holmes** [comment]
The broken breadcrumb link is now working correctly.
Thanks again!
-Scott
